### ISSUE TITLE
Doc snappy enabled by default

### ISSUE THREAD

**Issue by MadelineMurray** [ConsenSys/doc.teku#153]
PR: https://github.com/PegaSysEng/teku/pull/2552

> Documentation-wise most users shouldn't notice this change - it only affects if you're using a custom network, not one of the builtin ones.

**Comment by alexandratran** [comment]
According to @ajsutton, this change only affects users using custom networks from before Aug 11, 2020 (they need to explicitly disable snappy), but there are other compatibility changes due to the spec evolving since then that no one can be running a custom network from back then. So this probably does not need a doc update.
