### ISSUE TITLE
Can't link to specific version of REST API method

### ISSUE THREAD

**Issue by ajsutton** [ConsenSys/doc.teku#255]
The Teku REST API uses a URL like https://consensys.github.io/teku/#stable to link to a specific version but then when you click a link to a specific method it replaces the `#stable` with method name and winds up showing the latest master version again.

We should be able to a) navigate the docs showing the same version and b) link to a specific version of a specific method.

**Comment by ajsutton** [comment]
I suspect the key issue is that we needed to send a link to the particular method to a user and they wound up on the develop version.  The docs aren't particularly useful if we can't actually give people links to them - both the version and the method are important in that.

**Comment by NicolasMassart** [comment]
I will investigate this.

**Comment by NicolasMassart** [comment]
One way to deal with this, without breaking backward compatibility too much, would be to allow a version param in the URL.
For instance, currently we have  `https://consensys.github.io/teku/#stable` and then when pointing to a specific method we can have `https://consensys.github.io/teku/#operation/getEthV1ConfigSpec`.

Now imagine that we can still have these as retro compatibility but move the default way to `https://consensys.github.io/teku/?version=stable#operation/getEthV1ConfigSpec`, would it fit the need enough?

## Note
_I'm not suggesting the idea of having version in the path like `https://consensys.github.io/teku/stable/#operation/getEthV1ConfigSpec` because it's more complicated as we are hosting on Github Pages and we don't have control over manipulating URLs. It would require to actually create the folders for each version and duplicate the index file (we can't use symlinks either). Also I have plans for the near term future where an even better integration will be made with the doc site itself and we would not have different sites for doc and api but everything in the same and then use the main doc version selector._

**Comment by ajsutton** [comment]
Yeah I think moving version to a query param would work well.  I'm not too concerned with backwards compatibility of links to specific versions or methods to be honest but if we can keep old links working may as well.

**Comment by NicolasMassart** [comment]
Accidentally closed it...
